#!/usr/bin/osascript

-- End Work ... 現在のタブをアクティブなパネル 1 つだけに戻す。

tell application "Ghostty"
	activate

	try
		set win to front window
		set currentTab to selected tab of win
		set activePane to focused terminal of currentTab

		-- フォーカス中 terminal 以外を閉じる
		set allTerms to terminals of currentTab
		repeat with t in allTerms
			if (id of t) is not (id of activePane) then
				close t
			end if
		end repeat

		delay 0.2
		focus activePane
	on error errMsg
		return errMsg
	end try
end tell
